### ISSUE TITLE
aioch example not working

### ISSUE THREAD

**Issue by ghuname** [mymarilyn/aioch#3] opened 2019-10-20 14:37 UTC
Hi,

I have runned your example with modified selects:

```
from datetime import datetime

import asyncio
from aioch import Client


async def exec_progress():
    client = Client('localhost', port=2441)

    progress = await client.execute_with_progress('select 1')
    timeout = 20
    started_at = datetime.now()

    async for num_rows, total_rows in progress:
        done = num_rows / total_rows if total_rows else total_rows
        now = datetime.now()
        # Cancel query if it takes more than 20 seconds to process 50% of rows.
        if (now - started_at).total_seconds() > timeout and done < 0.5:
            await client.cancel()
            break
    else:
        rv = await progress.get_result()
        print(rv)


async def exec_no_progress():
    client = Client('localhost', port=2441)
    rv = await client.execute('select 2')
    print(rv)


loop = asyncio.get_event_loop()
loop.run_until_complete(asyncio.wait([exec_progress(), exec_no_progress()]))
```

but I got an error:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-a99ee321e210> in <module>
     31 
     32 loop = asyncio.get_event_loop()
---> 33 loop.run_until_complete(asyncio.wait([exec_progress(), exec_no_progress()]))

~\Miniconda3\lib\asyncio\base_events.py in run_until_complete(self, future)
    569         future.add_done_callback(_run_until_complete_cb)
    570         try:
--> 571             self.run_forever()
    572         except:
    573             if new_task and future.done() and not future.cancelled():

~\Miniconda3\lib\asyncio\base_events.py in run_forever(self)
    524         self._check_closed()
    525         if self.is_running():
--> 526             raise RuntimeError('This event loop is already running')
    527         if events._get_running_loop() is not None:
    528             raise RuntimeError(

RuntimeError: This event loop is already running
```

I don't get it what is wrong.

Regards.

**Comment by xzkostyan** [comment] 2019-10-20 16:37
Hi.

Can you provide environment (`pip freeze`) and python version?

**Comment by ghuname** [comment] 2019-10-20 21:40
```
(base) C:\Users\user>conda-env export
name: base
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - asn1crypto=0.24.0=py37_0
  - attrs=19.1.0=py37_1
  - backcall=0.1.0=py37_0
  - beautifulsoup4=4.8.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2019.8.28=0
  - certifi=2019.9.11=py37_0
  - cffi=1.12.3=py37h7a1dbc1_0
  - chardet=3.0.4=py37_1003
  - clickhouse-sqlalchemy=0.0.10=py_0
  - colorama=0.4.1=py37_0
  - conda=4.7.12=py37_0
  - conda-package-handling=1.3.11=py37_0
  - console_shortcut=0.1.1=3
  - cryptography=2.7=py37h7a1dbc1_0
  - cycler=0.10.0=py37_0
  - decorator=4.4.0=py37_1
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - freetype=2.9.1=ha9979f8_1
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha66f8fd_1
  - idna=2.8=py37_0
  - intel-openmp=2019.4=245
  - ipykernel=5.1.2=py37h39e3cac_0
  - ipython=7.7.0=py37h39e3cac_0
  - ipython-sql=0.3.9=py37_1000
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.1=py37_0
  - joblib=0.13.2=py37_0
  - jpeg=9b=hb83a4c4_2
  - json5=0.8.5=py_0
  - jsonschema=3.0.2=py37_0
  - jupyter_client=5.3.1=py_0
  - jupyter_core=4.5.0=py_0
  - jupyterlab=1.0.2=py37_0
  - jupyterlab_server=1.0.0=py_1
  - kiwisolver=1.1.0=py37ha925a31_0
  - krb5=1.16.1=hc04afaa_7
  - libarchive=3.3.3=h0643e63_5
  - libiconv=1.15=h1df5818_7
  - libpng=1.6.37=h2a8f88b_0
  - libpq=11.2=h3235a2c_0
  - libsodium=1.0.16=h9d3ae62_0
  - libxml2=2.9.9=h464c3ec_0
  - lz4=2.1.9=py37he774522_0
  - lz4-c=1.8.1.2=h2fa13f4_0
  - lzo=2.10=h6df0209_2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py37he774522_0
  - matplotlib=3.1.0=py37hc8f65d3_0
  - menuinst=1.4.16=py37he774522_0
  - mistune=0.8.4=py37he774522_0
  - mkl=2019.4=245
  - mkl-service=2.0.2=py37he774522_0
  - mkl_fft=1.0.14=py37h14836fe_0
  - mkl_random=1.0.2=py37h343c172_0
  - msys2-conda-epoch=20160418=1
  - natsort=6.0.0=py_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py37_0
  - nodejs=11.14.0=1
  - notebook=6.0.0=py37_0
  - numpy=1.16.4=py37h19fb1c0_0
  - numpy-base=1.16.4=py37hc3f5095_0
  - openssl=1.1.1d=he774522_3
  - pandas=0.25.1=py37ha925a31_0
  - pandas-profiling=1.4.1=0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.5.1=py_0
  - patsy=0.5.1=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=19.2.2=py37_0
  - powershell_shortcut=0.0.1=2
  - prettytable=0.7.2=py_3
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py37_0
  - psycopg2=2.8.3=py37h7a1dbc1_0
  - pycosat=0.6.3=py37hfa6e2cd_0
  - pycparser=2.19=py37_0
  - pygments=2.4.2=py_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py37h6538335_2
  - pyrsistent=0.14.11=py37he774522_0
  - pyscaffold=3.2.2=py_0
  - pysocks=1.7.0=py37_0
  - python=3.7.3=h8c8aaf0_0
  - python-dateutil=2.8.0=py37_0
  - python-libarchive-c=2.8=py37_13
  - pytz=2019.2=py_0
  - pywin32=223=py37hfa6e2cd_1
  - pywinpty=0.5.5=py37_1000
  - pyzmq=18.1.0=py37ha925a31_0
  - qgrid=1.1.1=py37_2
  - qt=5.9.7=vc14h73c81de_0
  - requests=2.22.0=py37_0
  - ruamel_yaml=0.15.46=py37hfa6e2cd_0
  - scikit-learn=0.21.2=py37h6288b17_0
  - scipy=1.2.1=py37h29ff71c_0
  - seaborn=0.9.0=py37_0
  - send2trash=1.5.0=py37_0
  - setuptools=41.0.1=py37_0
  - sip=4.19.8=py37h6538335_0
  - six=1.12.0=py37_0
  - soupsieve=1.9.2=py37_0
  - sqlalchemy=1.3.10=py37hfa6e2cd_0
  - sqlite=3.29.0=he774522_0
  - sqlparse=0.3.0=py_0
  - statsmodels=0.10.1=py37h8c2d366_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py37_0
  - tk=8.6.8=hfa6e2cd_0
  - tornado=6.0.3=py37he774522_0
  - tqdm=4.32.1=py_0
  - traitlets=4.3.2=py37_0
  - urllib3=1.24.2=py37_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.33.4=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - xlrd=1.2.0=py37_0
  - xz=5.2.4=h2fa13f4_4
  - yaml=0.1.7=hc54c509_2
  - zeromq=4.3.1=h33f27b4_3
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.3.7=h508b16e_0
  - pip:
    - aioch==0.0.1
    - aiodns==1.1.1
    - aiohttp==3.6.2
    - async-timeout==3.0.1
    - clickhouse-cityhash==1.0.2.3
    - clickhouse-driver==0.1.0
    - multidict==4.5.2
    - pycares==3.0.0
    - pycryptodome==3.9.0
    - yarl==1.1.0
prefix: C:\Users\user\Miniconda3


Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by xzkostyan** [comment] 2019-10-22 14:14
I can't reproduce problem. Can you run snippet in pure python virtualenv with aioch installed?

**Comment by Stanpol** [comment] 2019-10-25 10:11
`if else` is broken in the example:
```        
        if (now - started_at).total_seconds() > timeout and done < 0.5:
            await client.cancel()
            break
    else:
        rv = await progress.get_result()
        print(rv)
```

**Comment by ghuname** [comment] 2019-10-25 13:56
Looks like the problem is in ipython/ipykernel
(https://github.com/spyder-ide/spyder/issues/7096#issuecomment-397454652)

The same example works out of jupyter notebook.

**Comment by ghuname** [comment] 2019-10-26 11:23
Even with pure python, only exec_no_progress works.

exec_progress returns:

```
Task exception was never retrieved
future: <Task finished coro=<exec_progress() done, defined at async_ch.py:7> exception=TypeError("send_query() got an unexpected keyword argument 'settings'")>
Traceback (most recent call last):
  File "async_ch.py", line 10, in exec_progress
    progress = await client.execute_with_progress('select 1')
  File "C:\Users\user\Miniconda3\lib\site-packages\aioch\client.py", line 102, in execute_with_progress
    query_id=query_id, settings=settings
  File "C:\Users\user\Miniconda3\lib\site-packages\aioch\client.py", line 110, in process_ordinary_query_with_progress
    query_id=query_id, settings=settings
  File "C:\Users\user\Miniconda3\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: send_query() got an unexpected keyword argument 'settings'

```

File async_ch.py has contents:
```
from datetime import datetime

import asyncio
from aioch import Client


async def exec_progress():
    client = Client('localhost', port=2441, database='default')

    progress = await client.execute_with_progress('select 1')
    timeout = 20
    started_at = datetime.now()

    async for num_rows, total_rows in progress:
        done = num_rows / total_rows if total_rows else total_rows
        now = datetime.now()
        # Cancel query if it takes more than 20 seconds to process 50% of rows.
        if (now - started_at).total_seconds() > timeout and done < 0.5:
            await client.cancel()
            break
        else:
            rv = await progress.get_result()
            print(rv)


async def exec_no_progress():
    client = Client('localhost', port=2441, database='default')
    rv = await client.execute('select 2')
    print(rv)


loop = asyncio.get_event_loop()
loop.run_until_complete(asyncio.wait([exec_progress(), exec_no_progress()]))

```

**Comment by xzkostyan** [comment] 2019-10-26 12:09
Try to install from brach with updated cluckhouse-driver calls: https://github.com/mymarilyn/aioch/tree/update-interfaces

**Comment by xzkostyan** [comment] 2019-11-22 19:06
Fix for `TypeError` is released in 0.0.2 version.

**Comment by ghuname** [comment] 2019-11-24 17:13
> 
> 
> Try to install from brach with updated cluckhouse-driver calls: https://github.com/mymarilyn/aioch/tree/update-interfaces

The link you have provided doesn't exist.

**Comment by ghuname** [comment] 2019-11-24 17:27
> 
> 
> Fix for `TypeError` is released in 0.0.2 version.

(base) C:\Users\user>pip install aioch --upgrade
Requirement already up-to-date: aioch in c:\users\user\miniconda3\lib\site-packages (0.0.1)
Requirement already satisfied, skipping upgrade: clickhouse-driver>=0.0.6 in c:\users\user\miniconda3\lib\site-packages (from aioch) (0.1.1)
Requirement already satisfied, skipping upgrade: pytz in c:\users\user\miniconda3\lib\site-packages (from clickhouse-driver>=0.0.6->aioch) (2019.2)

**Comment by xzkostyan** [comment] 2019-11-24 20:14
@ghuname sorry about that. Package upload issue. Try again, please.

**Comment by ghuname** [comment] 2019-11-27 00:05
I have upgraded aioch to 0.0.2, the code from the start of the issue works with no problems from python interpreter, but from jupyter lab notebook, I get the result still have an error:


```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-326e7568a691> in <module>
     34 
     35 loop = asyncio.get_event_loop()
---> 36 loop.run_until_complete(asyncio.wait([exec_progress(), exec_no_progress()]))
     37 # loop.run_until_complete(asyncio.wait([exec_no_progress(), exec_no_progress()]))

~\Miniconda3\lib\asyncio\base_events.py in run_until_complete(self, future)
    564         future.add_done_callback(_run_until_complete_cb)
    565         try:
--> 566             self.run_forever()
    567         except:
    568             if new_task and future.done() and not future.cancelled():

~\Miniconda3\lib\asyncio\base_events.py in run_forever(self)
    519         self._check_closed()
    520         if self.is_running():
--> 521             raise RuntimeError('This event loop is already running')
    522         if events._get_running_loop() is not None:
    523             raise RuntimeError(

RuntimeError: This event loop is already running
[(2,)]
[(1,)]

```

As we can see the error is related to jupyter lab.

Anyway, on link https://markhneedham.com/blog/2019/05/10/jupyter-runtimeerror-this-event-loop-is-already-running/ is a solution.

In the first cell I should put:

import nest_asyncio
nest_asyncio.apply()

And now everything works.
Thank you very much  xzkostyan  for your help.

Best regards.

**Comment by xzkostyan** [comment] 2019-11-29 16:54
@ghuname should we close issue now?

**Comment by ghuname** [comment] 2019-11-30 17:01
Yes please.

**Closed as completed** 2019-11-30 20:16 UTC
